name: "README to index.html"
description: "Turn your README.md into a clean, styled GitHub Pages site using Pandoc and Simple.css — no Jekyll required."
author: Dave Cross (davorg)
branding:
  icon: "book-open"
  color: "blue"
inputs:
  readme:
    description: "Path to the Markdown source file"
    required: false
    default: "README.md"
  output:
    description: "Path to the generated HTML file"
    required: false
    default: "index.html"
  css_url:
    description: "CSS URL to link in the generated HTML"
    required: false
    default: "https://cdn.simplecss.org/simple.min.css"
  install_pandoc:
    description: "Whether to install pandoc via apt-get (true/false)"
    required: false
    default: "true"
  extra_pandoc_args:
    description: "Extra args passed to pandoc (space-separated)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install pandoc
      if: ${{ inputs.install_pandoc == 'true' }}
      shell: bash
      run: |
        set -euo pipefail

        if command -v pandoc >/dev/null 2>&1; then
          echo "pandoc already installed"
          exit 0
        fi

        if ! command -v apt-get >/dev/null 2>&1; then
          echo "ERROR: pandoc not found and apt-get is not available. Install pandoc in your job image, or set install_pandoc: false and install it yourself." >&2
          exit 1
        fi

        if command -v sudo >/dev/null 2>&1; then
          sudo apt-get update
          sudo apt-get install -y pandoc
        else
          apt-get update
          apt-get install -y pandoc
        fi

    - name: Build HTML from README
      shell: bash
      run: |
        set -euo pipefail

        readme="${{ inputs.readme }}"
        output="${{ inputs.output }}"
        css_url="${{ inputs.css_url }}"

        if [[ ! -f "$readme" ]]; then
          echo "ERROR: README file not found: $readme" >&2
          exit 1
        fi

        mkdir -p "$(dirname "$output")"

        # Extract first H1 (“# Title”) for the HTML <title>.
        # If not found, fall back to the README filename.
        pagetitle="$(sed -n 's/^# \{1,\}//p;q' "$readme" || true)"
        if [[ -z "${pagetitle}" ]]; then
          pagetitle="$(basename "$readme")"
        fi

        # shellcheck disable=SC2086
        pandoc -s --no-highlight \
          --css "$css_url" \
          --metadata "pagetitle=$pagetitle" \
          ${{ inputs.extra_pandoc_args }} \
          "$readme" -o "$output"

        echo "Generated: $output"
